export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_FETCHED = "USER_FETCHED";
export const USER_UPDATED = "USER_UPDATED";
export const USER_PASSWORD_UPDATED = "USER_PASSWORD_UPDATED";
